import * as React from "react";
import { render } from "react-dom";
import { remote } from "electron";
import "./app.global.scss";
import App from "./containers/App";
import { setConfig } from "react-hot-loader";

import { initializeSentry } from "./init-sentry";

if (!process.env.HOT) {
  // sentry kills hot reloading with react-hot-loader
  // possibly it's trying to report some RHL error... you do see them if you turn on
  // "Pause on caught exceptions" in the chrome debug tools
  // (note: it is possible to work around this by going away from the screen being modified)
  initializeSentry();
}

import { setupI18n } from "@lingui/core";

// messages.js is generated by the lingui cli "compile" command
import englishMessages from "../locale/en/messages.js";

//setup the i18n object with active language and catalogs
let i18n = setupI18n({
  language: "en",
  catalogs: {
    en: englishMessages
  }
});

setConfig({ logLevel: "debug" });

document.body.setAttribute("class", remote.process.platform);

render(<App />, document.getElementById("root"));

// if ((module as any).hot) {

//   render(
//     <ErrorBoundary>
//       <App />
//     </ErrorBoundary>,

//     document.getElementById("root")
//   );
// }

// const base = document.createElement("base");
// console.log("Setting base to " + locate("app"));
// base.setAttribute("href", locate("app"));
// document.getElementsByTagName("head")[0].appendChild(base);
