import fields from "../locale/fields.csv";
import { string } from "prop-types";
import { setupI18n, I18n } from "@lingui/core";

// messages.js are generated by ``yarn lingui-compile``
const englishMessages = require("../locale/en/messages.js");
const spanishMessages = require("../locale/es/messages.js");

export let i18n: I18n;

i18n = setupI18n({
  language: "es",
  catalogs: {
    //en: englishMessages,
    es: spanishMessages
  }
}).use("es");

export function lookup(english: string): string {
  const x = fields;
  const match = fields.find(f => f.En === english);
  if (match) {
    return match.Es;
  }
  return english;
}
